### ISSUE TITLE
issue with change password request

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project-api#10]
hello, I'm having issues with change password...

It can't find a module and it's having module build fails

  // $('#change-pwd').on('submit', function (event) {
  //   event.preventDefault();
  //   let data = getFormFields(this);
  //   authApi.changepwd(authUi.signOutsuccess, authUi.failure);
  //   console.log(data;
  // });

ncaught Error: Cannot find module "./auth/events.js"webpackMissingModule @ index.js:9(anonymous function) @ index.js:9(anonymous function) @ bundle.js:346__webpack_require__ @ bootstrap fc5b826…:50(anonymous function) @ index.js:8__webpack_require__ @ bootstrap fc5b826…:50webpackJsonpCallback @ bootstrap fc5b826…:21(anonymous function) @ bundle.js:1

**Comment by gaand** [comment]
Please close this issue and reopen [here](https://github.com/ga-wdi-boston/game-project/issues)

**Comment by RealWeeks** [comment]
Closed due to relevance.
