### ISSUE TITLE
Can't delete style.css

### ISSUE THREAD

**Issue by esthercordova** [ga-wdi-boston/game-project-api#12]
I'm trying to organize my files. i previously had my css in style.css but want to move it in index.scss now to conform with what we do in class.

It works without problems, but my api starts yelling at me. It tries for some reason to access the file that I  deleted. 

I solved it through having now am empty style.ss with all my css in index.scss but I would like to delete the empty file.

![screen shot 2016-06-02 at 11 46 09 am](https://cloud.githubusercontent.com/assets/13932794/15751374/e2875a64-28b7-11e6-8ba9-c7d0ac7823ef.png)

**Comment by payne-chris-r** [comment]
This issue belongs in the game-project repo (https://github.com/ga-wdi-boston/game-project/issues). Please close this issue here. If it IS still an issue you're having, please re-open in the correct repo. Thanks!

**Comment by payne-chris-r** [comment]
Thanks for closing this @esthercordova !
