### ISSUE TITLE
documentation requirement issue

### ISSUE THREAD

**Issue by mattb5** [ga-wdi-boston/game-project-api#13]
this is just following up on what i wrote in slack... just looking for some clarification.

From the requirements, 

"Visually display the results of retrieving game statistics, such as total games won by a user. (READ)"

I don't see anywhere in the documentation that visualizing the GET games statistics in console is not acceptable... wondering if to fully meet requirement we need to place the game statistics/history on the SPA itself or if "visually" seeing it in console is adequate.  

Thanks, 
Matt :)

**Comment by gaand** [comment]
@mattb5  This is the wrong repository for game project issues.

If you still need assistance with the requirements, please close this issue and open a new one on the `game-project` repository.  If not, please close this issue.  Thanks.
