### ISSUE TITLE
One on one

### ISSUE THREAD

**Issue by aneela06** [ga-wdi-boston/game-project-api#20]
I dont think I understand the API from the token-auths.  I was wondering if I could get some clarification.

**Comment by BenGitsCode** [comment]
Could you be more specific Aneela?

Please reference [this](https://github.com/ga-wdi-boston/project-issue-tracker-guide#how-to-use-the-issue-tracker)

I think you meant to open an issue [here](https://github.com/ga-wdi-boston/game-project/issues)

**Comment by aneela06** [comment]
Thanks Ben, I actually asked someone in class.  Sorry.

**Comment by aneela06** [comment]
Understood that I needed to copy and paste the auth token files into my tic tac toe new files.
