### ISSUE TITLE
I think the CHANGEPW method is not named correctly

### ISSUE THREAD

**Issue by sjruby** [ga-wdi-boston/game-project-api#22]
In the API guid teh change password method is listed as being: "changepw" for the URL path.

When I used that I got the error below:

ActionController::RoutingError (No route matches [PATCH] "/changepw/7"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'

By changing the path to "change-password" I got it to work.

**Comment by payne-chris-r** [comment]
New phone who dis? (aka, please put a profile photo on your gh acct). Please also move this issue to `game-project`

**Comment by sjruby** [comment]
Moving issue to the game project
