### ISSUE TITLE
From: Jeff "sign-out" link written as "signout"

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/game-project-api#6]
https://github.com/ga-wdi-boston/game-project-api#signout

**Comment by gaand** [comment]
@jrhorn424  Would you please provide clarification on this issue?  `signout` is the action, `/sign-out` is the path, I think consistently throughout the doc so I'm not sure what this issue is meant to address.

**Comment by jrhorn424** [comment]
@gaand I see. I saw the linked section and had the idea that `signout` was the endpoint. It's clear to me what was intended now.
