### ISSUE TITLE
change refs to formData

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/game-project-api#7]
Devs not using form data for this project

**Comment by gaand** [comment]
Closed by commit 928072baa8ed40a48b38d52657786d520c533cbc

**Comment by gaand** [comment]
@J-Weeks I should have asked you before closing.  Please confirm that the my changes to README.md address the issue.  Thanks.

**Comment by gaand** [comment]
@J-Weeks Since you never replied, I'm closing again.
