### ISSUE TITLE
Try to sign up and console shows error briefly then dissapears

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/game-project-api#8]
I try to to sign up and then console logs error for split second then disappears. Page then reads: Cannot POST /index.html

I checked urls and imports and all requires. Cant find the problem

``` js

//app-data.js
const app = {
  api: 'http://tic-tac-toe.wdibos.com'
};

//api.js
const signUp = (success, failure, data) => {
  $.ajax({
    method: 'POST',
    url: app.api + '/sign-up',
    data,
  }).done(success)
    .fail(failure);
};
```

**Comment by gaand** [comment]
This is the wrong repo for game-project issues.  Please open an issue [here](https://github.com/ga-wdi-boston/game-project/issues) and close this one out.
